@baseUrl = http://localhost:3000

### Create a film
POST {{baseUrl}}/films
Content-Type: application/json

{
    "title": "Nemo",
    "duration": 100,
    "budget": 94,
    "link": "https://www.imdb.com/title/tt0266543/"
}

### Read all films
GET {{baseUrl}}/films

### Read filtered films
GET {{baseUrl}}/films?minimum-duration=96

### Read one
GET {{baseUrl}}/films/2